USE [master]
GO

CREATE DATABASE [MovieBox]
GO
ALTER DATABASE [MovieBox] MODIFY FILE
( NAME = N'MovieBox', SIZE = 512MB, MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
GO

ALTER DATABASE [MovieBox] MODIFY FILE
( NAME = N'MovieBox_log', SIZE = 256MB, MAXSIZE = UNLIMITED, FILEGROWTH = 10% )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MovieBox].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MovieBox] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MovieBox] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MovieBox] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MovieBox] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MovieBox] SET ARITHABORT OFF 
GO

ALTER DATABASE [MovieBox] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [MovieBox] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MovieBox] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MovieBox] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MovieBox] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MovieBox] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MovieBox] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MovieBox] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MovieBox] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MovieBox] SET  ENABLE_BROKER 
GO

ALTER DATABASE [MovieBox] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MovieBox] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MovieBox] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MovieBox] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MovieBox] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MovieBox] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [MovieBox] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MovieBox] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MovieBox] SET  MULTI_USER 
GO

ALTER DATABASE [MovieBox] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MovieBox] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MovieBox] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MovieBox] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MovieBox] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MovieBox] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MovieBox] SET  READ_WRITE 
GO

USE [MovieBox]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Movies](
	[movie_id] [int] IDENTITY(1,1) NOT NULL,
	[imdb_id] [varchar](30) NULL,
	[title] [varchar](150) NOT NULL,
	[year] [varchar](10) NULL,
	[rated] [varchar](10) NULL,
	[released] [datetime] NOT NULL,
	[runtime] [varchar](50) NULL,
	[genre] [varchar](50) NULL,
	[director] [varchar](150) NULL,
	[writer] [varchar](350) NULL,
	[actors] [varchar](350) NULL,
	[plot] [varchar](250) NULL,
	[language] [varchar](150) NULL,
	[country] [varchar](100) NULL,
	[awards] [varchar](250) NULL,
	[poster] [varchar](250) NULL,
	[metascore] [int] NOT NULL,
	[imdb_rating] [float] NOT NULL,
	[imdb_votes] [int] NOT NULL,
	[type] [varchar](10) NULL,
	[dvd_release_date] [datetime] NOT NULL,
	[boxoffice] [varchar](250) NULL,
	[production] [varchar](150) NULL,
	[website] [varchar](150) NULL,
	[response] [bit] NOT NULL,
 CONSTRAINT [PK_Movies] PRIMARY KEY CLUSTERED 
(
	[movie_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Ratings](
	[rate_id] [int] IDENTITY(1,1) NOT NULL,
	[source] [varchar](150) NULL,
	[value] [varchar](25) NULL,
	[movie_id] [int] NULL,
 CONSTRAINT [PK_Ratings] PRIMARY KEY CLUSTERED 
(
	[rate_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Ratings]  WITH CHECK ADD  CONSTRAINT [FK_Ratings_Movies_movie_id] FOREIGN KEY([movie_id])
REFERENCES [dbo].[Movies] ([movie_id])
GO

ALTER TABLE [dbo].[Ratings] CHECK CONSTRAINT [FK_Ratings_Movies_movie_id]
GO
